#!/usr/bin/env python3
"""Export the macOS bundled catalog's standard short-context reference prices.

Uses Swift to evaluate the actual catalog, not a second table of copied rates.
Requires Python 3 and Swift 6 on a maintainer/CI machine; Windows builds consume
only the checked-in generated C# file and need neither Python nor Swift.
"""
from __future__ import annotations

import argparse
from decimal import Decimal
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SOURCES = [
    "Sources/QuotaLens/Core/CodexUsage/Pricing/PricingCatalog.swift",
    "Sources/QuotaLens/Core/CodexUsage/Pricing/HistoricalPricingCatalog.swift",
    "Sources/QuotaLens/Core/CodexUsage/Pricing/OpenAICurrentTierPricing.swift",
    "Sources/QuotaLens/Core/ClaudePricingCatalog.swift",
]
DESTINATION = ROOT / "windows/QuotaLens.Core/StandardPriceCatalog.g.cs"


def generate() -> str:
    if shutil.which("swift") is None:
        raise SystemExit("Swift 6 is required to regenerate the catalog, not to build Windows.")
    files = [(ROOT / name).read_text(encoding="utf-8").replace("\r\n", "\n") for name in SOURCES]
    marker = "struct ClaudePricingEvaluation:"
    if files[3].count(marker) != 1:
        raise SystemExit("Claude catalog boundary changed. Update the exporter explicitly.")
    claude = files[3].split(marker)[0].replace("import CryptoKit", "")
    exporter = """
struct Export: Encodable {
    let openAI: PricingCatalogModel
    let claudeVersion: String
    let claudePublishedAt: Int64
    let claude: [ClaudePricingEntry]
}
let export = Export(openAI: BundledPricingCatalog.defaultCatalog,
    claudeVersion: ClaudeBundledPricingCatalog.version,
    claudePublishedAt: ClaudeBundledPricingCatalog.publishedAtMs,
    claude: ClaudeBundledPricingCatalog.entries)
let encoder = JSONEncoder()
encoder.outputFormatting = [.sortedKeys]
FileHandle.standardOutput.write(try encoder.encode(export))
"""
    with tempfile.TemporaryDirectory(prefix="quotalens-catalog-") as directory:
        source = Path(directory) / "main.swift"
        source.write_text("\n".join(files[:3] + [claude, exporter]), encoding="utf-8")
        result = subprocess.run(["swift", str(source)], check=True, capture_output=True, text=True, timeout=180)
    catalog = json.loads(result.stdout, parse_float=Decimal)
    prices: dict[str, tuple[Decimal, Decimal, Decimal, Decimal]] = {}

    def put(alias: str, rates: tuple[Decimal, Decimal, Decimal, Decimal]) -> None:
        key = alias.strip().lower()
        if key in prices and prices[key] != rates:
            raise SystemExit(f"Conflicting explicit alias: {key}")
        prices[key] = rates

    published = catalog["openAI"]["publishedAt"]
    for model in catalog["openAI"]["models"]:
        matches = [r for r in model["rules"] if r.get("serviceTier") is None
                   and r["effectiveFromMs"] <= published
                   and (r.get("effectiveToMs") is None or published < r["effectiveToMs"])]
        if not matches:
            continue
        if len(matches) != 1:
            raise SystemExit(f"Ambiguous standard rule: {model['modelKey']}")
        rule = matches[0]
        divisor = Decimal(rule.get("rateDivisor", 1)) * 1000
        rates = tuple(Decimal(rule.get(field, 0)) / divisor for field in
                      ("inputNanoUsdPerToken", "cachedNanoUsdPerToken", "outputNanoUsdPerToken", "cacheWriteNanoUsdPerToken"))
        for alias in [model["modelKey"], *model.get("aliases", [])]:
            put(alias, rates)
    for model in catalog["claude"]:
        rates = tuple(Decimal(model[field]) / 1000 for field in ("inputRate", "cachedRate", "outputRate", "cacheWrite5mRate"))
        for alias in [model["modelKey"], *model["aliases"]]:
            put(alias, rates)
    digest = hashlib.sha256("\n".join(files).encode()).hexdigest()
    lines = ["// <auto-generated />", "// Regenerate: python3 windows/scripts/export-price-catalog.py",
             f"// Catalog source SHA256: {digest}", "namespace QuotaLens.Core;", "",
             "/// <summary>Reference-equivalent value at the bundled catalog's standard short-context rates.",
             "/// Not historical billing, Fast/Flex pricing or a subscription charge.</summary>",
             "public static class StandardPriceCatalog", "{",
             f'    public const string Version = "{catalog["openAI"]["catalogVersion"]} / {catalog["claudeVersion"]}";',
             f"    public const long PublishedAtMilliseconds = {published};",
             "    public static IReadOnlyList<Price> Entries { get; } = Array.AsReadOnly<Price>(["]
    for alias, rates in sorted(prices.items()):
        numbers = ", ".join(f"{value:f}m" for value in rates)
        lines.append(f"        new({json.dumps(alias)}, {numbers}),")
    lines += ["    ]);", "}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in catalog differs from Swift.")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != text:
            raise SystemExit("Windows pricing is out of sync. Regenerate and commit StandardPriceCatalog.g.cs.")
        print("PASS Windows reference prices match the macOS bundled catalog.")
    else:
        DESTINATION.write_text(text, encoding="utf-8")
        print(f"Generated {DESTINATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
