import Foundation

// 简体中文与英语由调用处提供，其余语言与应用现有语言集合保持一致。
let capacityForecastTranslations: [String: [AppLanguage: String]] = {
    let languages: [AppLanguage] = [.traditionalChinese, .japanese, .korean, .spanish, .german, .french, .portuguese, .portugueseBrazil]
    let rows: [String: [String]] = [
        "Waiting for cloud usage": ["等待雲端用量", "クラウド利用量の更新待ち", "클라우드 사용량 대기 중", "Esperando uso de la nube", "Cloud-Nutzungsdaten ausstehend", "En attente de l’usage cloud", "A aguardar utilização na nuvem", "Aguardando uso na nuvem"],
        "Waiting for usage": ["等待用量記錄", "利用記録を待機中", "사용 기록 대기 중", "Esperando registros de uso", "Nutzungsdaten ausstehend", "En attente d’utilisation", "A aguardar utilização", "Aguardando uso"],
        "Quota trend": ["額度趨勢", "利用枠の推移", "한도 추이", "Tendencia de cuota", "Kontingentverlauf", "Évolution du quota", "Tendência da quota", "Tendência da cota"],
        "Loading": ["載入中", "読み込み中", "불러오는 중", "Cargando", "Wird geladen", "Chargement", "A carregar", "Carregando"],
        "Quota Forecast": ["額度預測", "利用枠予測", "사용 한도 예측", "Previsión de cuota", "Kontingentprognose", "Prévision du quota", "Previsão de quota", "Previsão de cota"],
        "Estimate tokens per reset, track changes, and forecast the next cycle.": ["按每次重置評估可用 tokens，追蹤額度變化並預估下一週期。", "リセットごとのトークン数と変化を確認し、次の期間を予測します。", "초기화 주기별 토큰과 변화를 확인하고 다음 주기를 예측합니다.", "Estima tokens por reinicio, sigue los cambios y prevé el próximo ciclo.", "Tokens je Zurücksetzung schätzen, Änderungen verfolgen und den nächsten Zyklus prognostizieren.", "Estimez les tokens par réinitialisation, suivez les variations et prévoyez le prochain cycle.", "Estime tokens por reposição, acompanhe alterações e preveja o próximo ciclo.", "Estime tokens por redefinição, acompanhe mudanças e preveja o próximo ciclo."],
        "Estimates reflect usage habits, not an official fixed limit. Models and usage changes affect results.": ["這是按實際使用方式估算的可用量，並非官方固定上限。模型和使用方式變化會影響結果。", "推定は利用状況に基づき、公式の固定上限ではありません。モデルや使い方により変わります。", "사용 습관에 따른 추정치이며 공식 고정 한도가 아닙니다. 모델과 사용 방식에 따라 달라집니다.", "Son estimaciones según el uso, no límites oficiales fijos. Cambiar de modelo o uso afecta al resultado.", "Schätzungen beruhen auf der Nutzung, nicht auf einem offiziellen festen Limit. Modell und Nutzung beeinflussen das Ergebnis.", "Ces estimations dépendent de l’usage, pas d’une limite officielle fixe. Le modèle et l’usage influencent les résultats.", "As estimativas dependem da utilização, não de um limite oficial fixo. O modelo e a utilização afetam os resultados.", "As estimativas dependem do uso, não de um limite oficial fixo. O modelo e o uso afetam os resultados."],
        "History is unavailable. Refresh and try again.": ["歷史暫時無法讀取，請重新整理後再試。", "履歴を読み込めません。更新して再試行してください。", "기록을 불러올 수 없습니다. 새로고침 후 다시 시도하세요.", "Historial no disponible. Actualiza e inténtalo de nuevo.", "Verlauf nicht verfügbar. Aktualisieren Sie und versuchen Sie es erneut.", "Historique indisponible. Actualisez et réessayez.", "Histórico indisponível. Atualize e tente novamente.", "Histórico indisponível. Atualize e tente novamente."],
        "Collecting quota history": ["正在累積額度記錄", "利用枠の履歴を収集中", "한도 기록 수집 중", "Recopilando historial de cuota", "Kontingentverlauf wird gesammelt", "Collecte de l’historique du quota", "A recolher o histórico da quota", "Coletando histórico da cota"],
        "Keep the app running while using Codex. Estimates appear after enough usage; each reset adds a history point.": ["保持應用程式執行並正常使用 Codex。記錄到足夠用量後會顯示估算，每次重置後會增加歷史點。", "Codex の利用中はアプリを起動しておいてください。十分な利用量が集まると推定が表示され、リセットごとに履歴が追加されます。", "Codex를 사용하는 동안 앱을 실행해 두세요. 사용량이 쌓이면 추정치가 표시되고 초기화마다 기록이 추가됩니다.", "Mantén la app abierta al usar Codex. Las estimaciones aparecen con suficiente uso; cada reinicio añade un punto.", "Lassen Sie die App während der Codex-Nutzung laufen. Nach ausreichender Nutzung erscheinen Schätzungen; jede Zurücksetzung ergänzt den Verlauf.", "Gardez l’app ouverte pendant l’utilisation de Codex. Les estimations apparaissent après un usage suffisant ; chaque réinitialisation ajoute un point.", "Mantenha a aplicação aberta ao usar o Codex. As estimativas surgem com utilização suficiente; cada reposição acrescenta um ponto.", "Mantenha o aplicativo aberto ao usar o Codex. As estimativas aparecem com uso suficiente; cada redefinição adiciona um ponto."],
        "5-hour quota": ["5 小時額度", "5時間の利用枠", "5시간 한도", "Cuota de 5 horas", "5-Stunden-Kontingent", "Quota de 5 heures", "Quota de 5 horas", "Cota de 5 horas"],
        "Weekly quota": ["每週額度", "週間利用枠", "주간 한도", "Cuota semanal", "Wochenkontingent", "Quota hebdomadaire", "Quota semanal", "Cota semanal"],
        "Historical reference · Awaiting current quota": ["歷史參考 · 等待最新額度", "履歴参考・最新の利用枠を待機中", "과거 기록 · 현재 한도 대기 중", "Referencia histórica · Esperando cuota actual", "Historische Referenz · Aktuelles Kontingent ausstehend", "Référence historique · Quota actuel en attente", "Referência histórica · A aguardar quota atual", "Referência histórica · Aguardando cota atual"],
        "Estimated tokens per cycle": ["每週期預估總額度", "期間ごとの推定トークン総量", "주기별 예상 총 토큰", "Tokens estimados por ciclo", "Geschätzte Tokens je Zyklus", "Tokens estimés par cycle", "Tokens estimados por ciclo", "Tokens estimados por ciclo"],
        "In progress": ["估算中", "推定中", "추정 중", "En curso", "In Bearbeitung", "En cours", "Em curso", "Em andamento"],
        "Next cycle": ["下一週期", "次の期間", "다음 주기", "Próximo ciclo", "Nächster Zyklus", "Prochain cycle", "Próximo ciclo", "Próximo ciclo"],
        "Estimates start after observing at least 10% quota consumption.": ["至少記錄到 10% 的額度消耗後開始估算。", "利用枠の消費を10%以上記録すると推定を開始します。", "한도 소비량이 10% 이상 기록되면 추정을 시작합니다.", "La estimación empieza tras observar al menos un 10% de consumo.", "Schätzungen beginnen nach mindestens 10 % beobachtetem Verbrauch.", "L’estimation commence après au moins 10 % de consommation observée.", "As estimativas começam após observar pelo menos 10% de consumo.", "As estimativas começam após observar pelo menos 10% de consumo."],
        "Current cycle estimate": ["本週期預估總量", "現在の期間の推定総量", "현재 주기 예상 총량", "Estimación del ciclo actual", "Schätzung des aktuellen Zyklus", "Estimation du cycle actuel", "Estimativa do ciclo atual", "Estimativa do ciclo atual"],
        "Estimated remaining tokens": ["預計還可使用", "推定残りトークン", "예상 잔여 토큰", "Tokens restantes estimados", "Geschätzte verbleibende Tokens", "Tokens restants estimés", "Tokens restantes estimados", "Tokens restantes estimados"],
        "Next cycle estimate": ["下一週期預估", "次の期間の推定", "다음 주기 추정", "Estimación del próximo ciclo", "Schätzung des nächsten Zyklus", "Estimation du prochain cycle", "Estimativa do próximo ciclo", "Estimativa do próximo ciclo"],
        "%+.1f%% vs. last completed cycle": ["較最近已結束週期 %+.1f%%", "直近の完了期間比 %+.1f%%", "최근 완료 주기 대비 %+.1f%%", "%+.1f%% frente al último ciclo completo", "%+.1f%% zum letzten abgeschlossenen Zyklus", "%+.1f%% par rapport au dernier cycle terminé", "%+.1f%% face ao último ciclo concluído", "%+.1f%% em relação ao último ciclo concluído"],
        "Based on the latest level": ["暫按最近水準估算", "直近の水準に基づく推定", "최근 수준 기준 추정", "Según el nivel más reciente", "Auf Basis des letzten Niveaus", "Selon le niveau le plus récent", "Com base no nível mais recente", "Com base no nível mais recente"],
        "Waiting for more usage": ["等待更多用量", "利用データを待機中", "추가 사용량 대기 중", "Esperando más uso", "Weitere Nutzung abwarten", "En attente de plus d’usage", "A aguardar mais utilização", "Aguardando mais uso"],
        "Usage included in estimate": ["用於估算的用量", "推定に含まれる利用量", "추정에 포함된 사용량", "Uso incluido en la estimación", "In der Schätzung erfasste Nutzung", "Usage inclus dans l’estimation", "Utilização incluída na estimativa", "Uso incluído na estimativa"],
        "Observed consumption: %.1f%%": ["已記錄額度消耗：%.1f%%", "記録された消費：%.1f%%", "기록된 한도 소비: %.1f%%", "Consumo observado: %.1f%%", "Beobachteter Verbrauch: %.1f%%", "Consommation observée : %.1f%%", "Consumo observado: %.1f%%", "Consumo observado: %.1f%%"],
        "Change: %@ tokens (%+.1f%%)": ["較上週期：%@ tokens（%+.1f%%）", "前期間比：%@ tokens（%+.1f%%）", "이전 주기 대비: %@ tokens (%+.1f%%)", "Cambio: %@ tokens (%+.1f%%)", "Änderung: %@ Tokens (%+.1f%%)", "Variation : %@ tokens (%+.1f%%)", "Variação: %@ tokens (%+.1f%%)", "Variação: %@ tokens (%+.1f%%)"],
        "Some periods are missing. Only matched usage and quota changes are used.": ["部分時段未記錄，僅使用時間對應的用量和額度變化估算。", "一部の期間は未記録です。対応する利用量と利用枠の変化のみで推定します。", "일부 기간의 기록이 없습니다. 시간이 일치하는 사용량과 한도 변화만 사용합니다.", "Faltan algunos periodos. Solo se usan datos de uso y cuota del mismo intervalo.", "Einige Zeiträume fehlen. Nur zeitlich passende Nutzungs- und Kontingentänderungen werden verwendet.", "Certaines périodes manquent. Seuls l’usage et les variations de quota correspondants sont utilisés.", "Faltam alguns períodos. Apenas são usadas alterações de utilização e quota correspondentes.", "Faltam alguns períodos. Apenas mudanças correspondentes de uso e cota são usadas."],
        "Scheduled reset": ["正常重置", "予定どおりのリセット", "정기 초기화", "Reinicio programado", "Planmäßige Zurücksetzung", "Réinitialisation prévue", "Reposição programada", "Redefinição programada"],
        "Early quota recovery": ["提前恢復額度", "利用枠の早期回復", "한도 조기 복구", "Recuperación anticipada", "Vorzeitige Wiederherstellung", "Rétablissement anticipé", "Recuperação antecipada", "Recuperação antecipada"],
        "Plan changed": ["方案變更", "プラン変更", "요금제 변경", "Plan cambiado", "Tarif geändert", "Forfait modifié", "Plano alterado", "Plano alterado"],
        "Awaiting reset confirmation": ["等待重置確認", "リセットの確認待ち", "초기화 확인 대기 중", "Esperando confirmar el reinicio", "Bestätigung der Zurücksetzung ausstehend", "Confirmation de réinitialisation en attente", "A aguardar confirmação da reposição", "Aguardando confirmação da redefinição"]
    ]
    return rows.mapValues { Dictionary(uniqueKeysWithValues: zip(languages, $0)) }
}()
