import Foundation

let resetHistoryTranslations: [String: [AppLanguage: String]] = {
    let languages: [AppLanguage] = [.traditionalChinese, .japanese, .korean, .spanish, .german, .french, .portuguese, .portugueseBrazil]
    let rows: [String: [String]] = [
        "See what needs attention. View details without leaving this page.": ["先看需要關注的事，詳情可在目前頁面查看。", "要確認の項目と詳細をこのページで確認できます。", "확인이 필요한 항목과 상세를 현재 페이지에서 확인하세요.", "Consulta lo que requiere atención y los detalles sin salir de esta página.", "Hinweise und Details ansehen, ohne diese Seite zu verlassen.", "Consultez les points à surveiller et leurs détails sans quitter cette page.", "Veja o que requer atenção e os detalhes sem sair desta página.", "Veja o que requer atenção e os detalhes sem sair desta página."],
        "View accounts across tools. Details open without leaving this page.": ["跨工具查看帳號，詳情不會離開目前頁面。", "ツール横断のアカウント詳細をこのページで確認できます。", "도구 전체 계정의 상세를 현재 페이지에서 확인하세요.", "Consulta cuentas de todas las herramientas sin salir de esta página.", "Toolübergreifende Kontodetails auf dieser Seite ansehen.", "Consultez les détails des comptes sans quitter cette page.", "Veja contas de todas as ferramentas sem sair desta página.", "Veja contas de todas as ferramentas sem sair desta página."],
        "Quota details": ["額度詳情", "利用枠の詳細", "한도 상세", "Detalles de cuota", "Kontingentdetails", "Détails du quota", "Detalhes da quota", "Detalhes da cota"],
        "Accounts with refresh tokens renew automatically. Renewing imported shared tokens may affect other clients' subsequent refreshes.": ["有刷新權杖的帳號會自動續期；匯入共用權杖的續期可能影響其他用戶端之後的刷新。", "更新トークンがあるアカウントは自動更新されます。共有トークンの更新は他クライアントに影響する場合があります。", "갱신 토큰이 있는 계정은 자동 갱신됩니다. 공유 토큰 갱신은 다른 클라이언트의 갱신에 영향을 줄 수 있습니다.", "Las cuentas con refresh token se renuevan automáticamente. Renovar tokens compartidos puede afectar a otros clientes.", "Konten mit Refresh-Token werden automatisch erneuert. Geteilte Tokens können andere Clients beeinflussen.", "Les comptes avec jeton de renouvellement se renouvellent automatiquement. Les jetons partagés peuvent affecter les autres clients.", "Contas com refresh token renovam automaticamente. Tokens partilhados podem afetar outros clientes.", "Contas com refresh token renovam automaticamente. Tokens compartilhados podem afetar outros clientes."],
        "Automatic renewal enabled": ["自動續期已啟用", "自動更新が有効", "자동 갱신 활성화", "Renovación automática activada", "Automatische Erneuerung aktiv", "Renouvellement automatique activé", "Renovação automática ativa", "Renovação automática ativa"],
        "Reset card granted": ["獲得重置卡", "リセットカード獲得", "초기화 카드 획득", "Tarjeta de reinicio recibida", "Reset-Karte erhalten", "Carte de réinitialisation reçue", "Cartão de reposição recebido", "Cartão de redefinição recebido"],
        "Reset card used": ["使用重置卡", "リセットカード使用", "초기화 카드 사용", "Tarjeta de reinicio utilizada", "Reset-Karte verwendet", "Carte de réinitialisation utilisée", "Cartão de reposição utilizado", "Cartão de redefinição usado"],
        "Reset card expired": ["重置卡到期", "リセットカード期限切れ", "초기화 카드 만료", "Tarjeta de reinicio caducada", "Reset-Karte abgelaufen", "Carte de réinitialisation expirée", "Cartão de reposição expirado", "Cartão de redefinição expirado"],
        "History could not be loaded. The last result was retained.": ["歷史讀取失敗，保留上次結果。", "履歴を読み込めません。前回の結果を保持しています。", "기록을 불러오지 못했습니다. 이전 결과를 유지합니다.", "No se pudo cargar el historial. Se conserva el último resultado.", "Verlauf konnte nicht geladen werden. Letztes Ergebnis bleibt erhalten.", "Impossible de charger l’historique. Le dernier résultat est conservé.", "Não foi possível carregar o histórico. Último resultado mantido.", "Não foi possível carregar o histórico. Último resultado mantido."],
        "Reset card history": ["重置卡歷史", "リセットカード履歴", "초기화 카드 기록", "Historial de tarjetas de reinicio", "Reset-Kartenverlauf", "Historique des cartes de réinitialisation", "Histórico de cartões de reposição", "Histórico de cartões de redefinição"],
        "Used only": ["僅已使用", "使用済みのみ", "사용한 항목만", "Solo utilizadas", "Nur verwendete", "Utilisées uniquement", "Apenas utilizados", "Apenas usados"],
        "API history window": ["API 歷史範圍", "API履歴の期間", "API 기록 기간", "Periodo del historial API", "API-Verlaufszeitraum", "Période de l’historique API", "Período do histórico API", "Período do histórico da API"],
        "History is read-only; it does not consume or restore reset cards.": ["歷史僅供查看，不會消耗或恢復重置卡。", "履歴は閲覧専用です。カードを消費・復元しません。", "기록은 조회 전용이며 카드를 사용하거나 복원하지 않습니다.", "El historial es de solo lectura; no consume ni restaura tarjetas.", "Der Verlauf ist schreibgeschützt; Karten werden weder verbraucht noch wiederhergestellt.", "L’historique est en lecture seule ; aucune carte n’est consommée ou restaurée.", "O histórico é só de leitura; não consome nem restaura cartões.", "O histórico é somente leitura; não consome nem restaura cartões."],
        "No reset card history in this window": ["此範圍內沒有重置卡歷史", "この期間の履歴はありません", "이 기간에 초기화 카드 기록이 없습니다", "Sin historial en este periodo", "Kein Verlauf in diesem Zeitraum", "Aucun historique sur cette période", "Sem histórico neste período", "Sem histórico neste período"],
        "Load more": ["載入更多", "さらに読み込む", "더 불러오기", "Cargar más", "Mehr laden", "Charger plus", "Carregar mais", "Carregar mais"],
    ]
    return rows.mapValues { Dictionary(uniqueKeysWithValues: zip(languages, $0)) }
}()
