import Foundation

let accountTransferTranslations: [String: [AppLanguage: String]] = {
    let languages: [AppLanguage] = [.traditionalChinese, .japanese, .korean, .spanish, .german, .french, .portuguese, .portugueseBrazil]
    let rows: [String: [String]] = [
        "Credential file is missing. Import or authorize again.": ["憑證檔案缺失，請重新匯入或授權。", "認証ファイルがありません。再インポートまたは認証してください。", "인증 파일이 없습니다. 다시 가져오거나 인증하세요.", "Falta el archivo de credenciales. Importa o autoriza de nuevo.", "Zugangsdaten-Datei fehlt. Erneut importieren oder autorisieren.", "Fichier d’identifiants manquant. Réimportez ou autorisez à nouveau.", "Falta o ficheiro de credenciais. Importe ou autorize novamente.", "Falta o arquivo de credenciais. Importe ou autorize novamente."],
        "Access token expired. Renew it or authorize again.": ["存取權杖已到期，請續期或重新授權。", "アクセストークンが期限切れです。更新または再認証してください。", "액세스 토큰이 만료되었습니다. 갱신하거나 다시 인증하세요.", "El token de acceso caducó. Renuévalo o autoriza de nuevo.", "Zugriffstoken abgelaufen. Erneuern oder erneut autorisieren.", "Jeton d’accès expiré. Renouvelez-le ou autorisez à nouveau.", "O token de acesso expirou. Renove ou autorize novamente.", "O token de acesso expirou. Renove ou autorize novamente."],
        "This credential needs renewal. Allow renewal for imported credentials and retry, or authorize independently.": ["此憑證需要續期；允許匯入憑證續期後重試，或獨立授權。", "更新が必要です。インポート認証の更新を許可して再試行するか、独立認証してください。", "갱신이 필요합니다. 가져온 인증 정보 갱신을 허용한 뒤 재시도하거나 별도로 인증하세요.", "Requiere renovación. Permite renovar credenciales importadas y reintenta, o autoriza por separado.", "Erneuerung erforderlich. Importierte Zugangsdaten zur Erneuerung freigeben und erneut versuchen oder separat autorisieren.", "Renouvellement requis. Autorisez le renouvellement des identifiants importés puis réessayez, ou autorisez séparément.", "Requer renovação. Permita renovar credenciais importadas e tente novamente, ou autorize separadamente.", "Requer renovação. Permita renovar credenciais importadas e tente novamente, ou autorize separadamente."],
        "Authorization was rejected by the server. Authorize again.": ["授權遭伺服器拒絕，請重新授權。", "サーバーが認証を拒否しました。再認証してください。", "서버가 인증을 거부했습니다. 다시 인증하세요.", "El servidor rechazó la autorización. Autoriza de nuevo.", "Autorisierung vom Server abgelehnt. Erneut autorisieren.", "Autorisation refusée par le serveur. Autorisez à nouveau.", "O servidor rejeitou a autorização. Autorize novamente.", "O servidor rejeitou a autorização. Autorize novamente."],
        "Unsupported credential format. Import account JSON or a valid token.": ["不支援此憑證格式，請匯入帳號 JSON 或有效權杖。", "非対応の形式です。アカウントJSONまたは有効なトークンをインポートしてください。", "지원하지 않는 형식입니다. 계정 JSON 또는 유효한 토큰을 가져오세요.", "Formato no compatible. Importa JSON de cuenta o un token válido.", "Nicht unterstütztes Format. Konto-JSON oder gültiges Token importieren.", "Format non pris en charge. Importez un JSON de compte ou un jeton valide.", "Formato não suportado. Importe JSON da conta ou um token válido.", "Formato não suportado. Importe JSON da conta ou um token válido."],
        "Account identity does not match. This credential was not saved.": ["帳號身分不符，未儲存此憑證。", "アカウントが一致しないため保存しませんでした。", "계정이 일치하지 않아 저장하지 않았습니다.", "La identidad no coincide. No se guardaron las credenciales.", "Kontoidentität stimmt nicht überein. Zugangsdaten nicht gespeichert.", "Identité du compte différente. Identifiants non enregistrés.", "A identidade não corresponde. Credenciais não guardadas.", "A identidade não corresponde. Credenciais não salvas."],
        "Accounts in this file belong to a different tool.": ["檔案中的帳號屬於其他工具。", "ファイルのアカウントは別のツール用です。", "파일의 계정은 다른 도구에 속합니다.", "Las cuentas pertenecen a otra herramienta.", "Konten gehören zu einem anderen Tool.", "Les comptes appartiennent à un autre outil.", "As contas pertencem a outra ferramenta.", "As contas pertencem a outra ferramenta."],
        "This authorization type or OAuth client is not supported for quota queries.": ["此授權類型或 OAuth 用戶端暫不支援額度查詢。", "この認証方式またはOAuthクライアントでの利用枠照会には非対応です。", "이 인증 유형 또는 OAuth 클라이언트의 한도 조회는 지원하지 않습니다.", "Este tipo de autorización o cliente OAuth no admite consultas de cuota.", "Dieser Autorisierungstyp oder OAuth-Client unterstützt keine Kontingentabfragen.", "Ce type d’autorisation ou client OAuth ne prend pas en charge les requêtes de quota.", "Este tipo de autorização ou cliente OAuth não suporta consultas de quota.", "Este tipo de autorização ou cliente OAuth não suporta consultas de cota."],
        "File is empty or exceeds import limits (8 MB, 200 accounts).": ["檔案為空或超過匯入限制（8 MB、200 個帳號）。", "ファイルが空か、上限（8 MB、200アカウント）を超えています。", "파일이 비어 있거나 한도(8 MB, 200개 계정)를 초과합니다.", "Archivo vacío o superior al límite (8 MB, 200 cuentas).", "Datei leer oder Limit überschritten (8 MB, 200 Konten).", "Fichier vide ou limite dépassée (8 Mo, 200 comptes).", "Ficheiro vazio ou acima do limite (8 MB, 200 contas).", "Arquivo vazio ou acima do limite (8 MB, 200 contas)."],
        "Local encrypted credentials could not be read or saved. Check storage permissions.": ["無法讀取或儲存本機加密憑證，請檢查儲存權限。", "ローカル暗号化認証情報の読み書きに失敗しました。権限を確認してください。", "로컬 암호화 인증 정보를 읽거나 저장하지 못했습니다. 권한을 확인하세요.", "No se pudieron leer o guardar las credenciales cifradas. Revisa los permisos.", "Lokale verschlüsselte Zugangsdaten nicht lesbar oder speicherbar. Berechtigungen prüfen.", "Impossible de lire ou enregistrer les identifiants chiffrés. Vérifiez les permissions.", "Não foi possível ler ou guardar as credenciais encriptadas. Verifique as permissões.", "Não foi possível ler ou salvar as credenciais criptografadas. Verifique as permissões."],
        "An account operation is in progress. Try again shortly.": ["正在處理帳號，請稍後重試。", "アカウント処理中です。少し待って再試行してください。", "계정 처리 중입니다. 잠시 후 다시 시도하세요.", "Hay una operación en curso. Reintenta en breve.", "Kontovorgang läuft. Gleich erneut versuchen.", "Une opération est en cours. Réessayez bientôt.", "Operação em curso. Tente novamente em breve.", "Operação em andamento. Tente novamente em breve."],
        "Query temporarily failed. Check the network or try again later.": ["查詢暫時失敗，請檢查網路或稍後重試。", "一時的に取得できません。ネットワークを確認するか再試行してください。", "일시적으로 조회에 실패했습니다. 네트워크를 확인하거나 나중에 시도하세요.", "Fallo temporal. Revisa la red o reintenta más tarde.", "Abfrage vorübergehend fehlgeschlagen. Netzwerk prüfen oder später versuchen.", "Échec temporaire. Vérifiez le réseau ou réessayez plus tard.", "Falha temporária. Verifique a rede ou tente mais tarde.", "Falha temporária. Verifique a rede ou tente mais tarde."],
        "Imported/updated %d · unchanged %d · failed %d": ["匯入或更新 %d 項 · 未變更 %d 項 · 失敗 %d 項", "インポート/更新 %d · 変更なし %d · 失敗 %d", "가져옴/업데이트 %d · 변경 없음 %d · 실패 %d", "Importados/actualizados %d · sin cambios %d · fallidos %d", "Importiert/aktualisiert %d · unverändert %d · fehlgeschlagen %d", "Importés/mis à jour %d · inchangés %d · échecs %d", "Importados/atualizados %d · sem alterações %d · falhas %d", "Importados/atualizados %d · sem alterações %d · falhas %d"],
        "Allow renewal of imported credentials": ["允許匯入憑證續期", "インポート認証情報の更新を許可", "가져온 인증 정보 갱신 허용", "Permitir renovar credenciales importadas", "Erneuerung importierter Zugangsdaten erlauben", "Autoriser le renouvellement des identifiants importés", "Permitir renovar credenciais importadas", "Permitir renovar credenciais importadas"],
        "Renewal may rotate tokens shared with another client. Independent grants renew automatically; imported credentials require permission.": ["續期可能輪換與其他用戶端共用的權杖；獨立授權自動續期，匯入憑證需明確允許。", "更新すると他クライアントと共有するトークンが変更される場合があります。独立認証は自動更新、インポート認証は許可が必要です。", "갱신 시 다른 클라이언트와 공유하는 토큰이 교체될 수 있습니다. 독립 인증은 자동 갱신하며 가져온 인증은 허용이 필요합니다.", "La renovación puede rotar tokens compartidos. Las autorizaciones independientes se renuevan automáticamente; las importadas requieren permiso.", "Erneuerung kann gemeinsam genutzte Tokens rotieren. Separate Autorisierungen werden automatisch erneuert; Importe erfordern Zustimmung.", "Le renouvellement peut remplacer des jetons partagés. Les autorisations indépendantes se renouvellent automatiquement ; les imports nécessitent un accord.", "A renovação pode substituir tokens partilhados. Autorizações independentes renovam automaticamente; importadas requerem permissão.", "A renovação pode substituir tokens compartilhados. Autorizações independentes renovam automaticamente; importadas requerem permissão."],
        "Import failure details": ["匯入失敗詳情", "インポート失敗の詳細", "가져오기 실패 상세", "Detalles de fallos de importación", "Details zu Importfehlern", "Détails des échecs d’import", "Detalhes das falhas de importação", "Detalhes das falhas de importação"],
        "Last verified": ["最近驗證", "最終検証", "마지막 검증", "Última verificación", "Zuletzt geprüft", "Dernière vérification", "Última verificação", "Última verificação"],
        "Access token expiry": ["存取權杖到期", "アクセストークン期限", "액세스 토큰 만료", "Caducidad del token de acceso", "Ablauf des Zugriffstokens", "Expiration du jeton d’accès", "Expiração do token de acesso", "Expiração do token de acesso"],
        "Allow renewal for this account": ["允許此帳號續期", "このアカウントの更新を許可", "이 계정의 갱신 허용", "Permitir renovación de esta cuenta", "Erneuerung für dieses Konto erlauben", "Autoriser le renouvellement de ce compte", "Permitir renovação desta conta", "Permitir renovação desta conta"],
        "Independent authorization renews automatically": ["獨立授權自動續期", "独立認証は自動更新されます", "독립 인증 자동 갱신", "La autorización independiente se renueva automáticamente", "Separate Autorisierung wird automatisch erneuert", "L’autorisation indépendante se renouvelle automatiquement", "A autorização independente renova automaticamente", "A autorização independente renova automaticamente"],
        "Export accounts": ["匯出帳號", "アカウントをエクスポート", "계정 내보내기", "Exportar cuentas", "Konten exportieren", "Exporter les comptes", "Exportar contas", "Exportar contas"],
        "Export": ["匯出", "エクスポート", "내보내기", "Exportar", "Exportieren", "Exporter", "Exportar", "Exportar"],
        "Confirm export": ["確認匯出", "エクスポートを確認", "내보내기 확인", "Confirmar exportación", "Export bestätigen", "Confirmer l’export", "Confirmar exportação", "Confirmar exportação"],
        "The export contains plaintext tokens that grant account access. Do not upload, publish, or share it with others.": ["匯出檔含有可存取帳號的明文 Token，請勿上傳、公開或傳給他人。", "エクスポートにはアカウントにアクセス可能な平文トークンが含まれます。アップロード、公開、共有しないでください。", "내보내기 파일에는 계정 접근이 가능한 평문 토큰이 포함됩니다. 업로드, 공개 또는 공유하지 마세요.", "El archivo contiene tokens en texto plano que dan acceso a la cuenta. No lo subas, publiques ni compartas.", "Der Export enthält Klartext-Tokens für den Kontozugriff. Nicht hochladen, veröffentlichen oder weitergeben.", "L’export contient des jetons en clair donnant accès au compte. Ne le téléversez, publiez ni partagez.", "A exportação contém tokens em texto simples que dão acesso à conta. Não envie, publique nem partilhe.", "A exportação contém tokens em texto simples que dão acesso à conta. Não envie, publique nem compartilhe."],
        "Accounts exported. Keep the file secure.": ["帳號已匯出，請妥善保管檔案。", "エクスポート完了。ファイルを安全に保管してください。", "계정을 내보냈습니다. 파일을 안전하게 보관하세요.", "Cuentas exportadas. Guarda el archivo de forma segura.", "Konten exportiert. Datei sicher aufbewahren.", "Comptes exportés. Conservez le fichier en sécurité.", "Contas exportadas. Guarde o ficheiro em segurança.", "Contas exportadas. Guarde o arquivo em segurança."],
        "Export did not complete.": ["匯出未完成。", "エクスポート未完了。", "내보내기가 완료되지 않았습니다.", "La exportación no se completó.", "Export nicht abgeschlossen.", "Export non terminé.", "Exportação não concluída.", "Exportação não concluída."],
    ]
    return rows.mapValues { Dictionary(uniqueKeysWithValues: zip(languages, $0)) }
}()
