import Foundation

let diagnosticsTranslations: [String: [AppLanguage: String]] = {
    let languages: [AppLanguage] = [.traditionalChinese, .japanese, .korean, .spanish, .german, .french, .portuguese, .portugueseBrazil]
    let rows: [String: [String]] = [
        "Problem details": ["問題詳情", "問題の詳細", "문제 상세", "Detalles del problema", "Problemdetails", "Détails du problème", "Detalhes do problema", "Detalhes do problema"],
        "This issue is no longer being reported.": ["目前未再回報此問題。", "この問題は現在報告されていません。", "현재 이 문제가 보고되지 않습니다.", "Este problema ya no se notifica.", "Dieses Problem wird nicht mehr gemeldet.", "Ce problème n’est plus signalé.", "Este problema já não é reportado.", "Este problema não é mais relatado."],
        "The affected source count is unavailable; it must not be shown as zero.": ["無法確認受影響來源數量，不能顯示為 0。", "影響を受けるソース数は不明です。0ではありません。", "영향받는 소스 수를 알 수 없으며 0으로 표시하지 않습니다.", "Se desconoce el número de fuentes afectadas; no equivale a cero.", "Die Anzahl betroffener Quellen ist unbekannt, nicht null.", "Le nombre de sources affectées est inconnu, et non nul.", "O número de fontes afetadas é desconhecido, não zero.", "O número de fontes afetadas é desconhecido, não zero."],
        "Retry reading": ["重新讀取", "再読み込み", "다시 읽기", "Reintentar lectura", "Erneut lesen", "Relire", "Repetir leitura", "Tentar ler novamente"],
        "This is a startup storage issue. Restart to check again; the database will not be cleared automatically.": ["這是啟動時的儲存問題；重新啟動可再次檢查，不會自動清空資料庫。", "起動時のストレージの問題です。再起動して再確認してください。データベースは自動削除されません。", "시작 시 저장소 문제입니다. 다시 시작하여 확인하세요. 데이터베이스는 자동 삭제되지 않습니다.", "Problema de almacenamiento al iniciar. Reinicia para comprobar; la base de datos no se borrará automáticamente.", "Speicherproblem beim Start. Zum Prüfen neu starten; die Datenbank wird nicht automatisch gelöscht.", "Problème de stockage au démarrage. Redémarrez pour vérifier ; la base ne sera pas effacée automatiquement.", "Problema de armazenamento no arranque. Reinicie para verificar; a base de dados não será apagada automaticamente.", "Problema de armazenamento na inicialização. Reinicie para verificar; o banco de dados não será apagado automaticamente."],
        "Scan issues": ["掃描問題", "スキャンの問題", "스캔 문제", "Problemas de escaneo", "Scan-Probleme", "Problèmes d’analyse", "Problemas de análise", "Problemas de verificação"],
        "Unreadable sources": ["讀取失敗來源", "読み取り失敗ソース", "읽기 실패 소스", "Fuentes ilegibles", "Nicht lesbare Quellen", "Sources illisibles", "Fontes ilegíveis", "Fontes ilegíveis"],
        "Incompatible sources": ["格式不相容來源", "非対応形式のソース", "호환되지 않는 소스", "Fuentes incompatibles", "Inkompatible Quellen", "Sources incompatibles", "Fontes incompatíveis", "Fontes incompatíveis"],
        "Last checked": ["最近檢查", "最終確認", "최근 확인", "Última comprobación", "Zuletzt geprüft", "Dernière vérification", "Última verificação", "Última verificação"],
        "Not checked yet; this does not mean there are no issues.": ["尚未檢查，不代表沒有問題。", "未確認です。問題がないという意味ではありません。", "아직 확인하지 않았으며 문제가 없다는 뜻은 아닙니다.", "Aún no comprobado; no significa que no haya problemas.", "Noch nicht geprüft; dies bedeutet nicht, dass keine Probleme vorliegen.", "Pas encore vérifié ; cela ne signifie pas qu’il n’y a aucun problème.", "Ainda não verificado; não significa ausência de problemas.", "Ainda não verificado; não significa ausência de problemas."],
        "This Antigravity scan reported no issues.": ["本次 Antigravity 掃描未回報問題。", "今回のAntigravityスキャンでは問題は報告されませんでした。", "이번 Antigravity 스캔에서 문제가 보고되지 않았습니다.", "Este escaneo de Antigravity no notificó problemas.", "Dieser Antigravity-Scan meldete keine Probleme.", "Cette analyse Antigravity n’a signalé aucun problème.", "Esta análise Antigravity não reportou problemas.", "Esta verificação Antigravity não relatou problemas."],
        "These sources were not fully updated; related statistics retain the last result.": ["以下來源未完整更新，相關統計保留上次結果。", "以下のソースは完全に更新されず、関連統計は前回の結果を保持しています。", "이 소스들은 완전히 업데이트되지 않아 관련 통계는 이전 결과를 유지합니다.", "Estas fuentes no se actualizaron por completo; se conservan las estadísticas anteriores.", "Diese Quellen wurden nicht vollständig aktualisiert; die bisherigen Statistiken bleiben erhalten.", "Ces sources n’ont pas été entièrement actualisées ; les statistiques précédentes sont conservées.", "Estas fontes não foram totalmente atualizadas; as estatísticas anteriores são mantidas.", "Estas fontes não foram totalmente atualizadas; as estatísticas anteriores são mantidas."],
        "Scan incomplete": ["掃描未完成", "スキャン未完了", "스캔 미완료", "Escaneo incompleto", "Scan unvollständig", "Analyse incomplète", "Análise incompleta", "Verificação incompleta"],
        "Not checked": ["未檢查", "未確認", "미확인", "Sin comprobar", "Nicht geprüft", "Non vérifié", "Não verificado", "Não verificado"],
        "Unknown": ["未知", "不明", "알 수 없음", "Desconocido", "Unbekannt", "Inconnu", "Desconhecido", "Desconhecido"],
        "View issues": ["查看問題", "問題を表示", "문제 보기", "Ver problemas", "Probleme ansehen", "Voir les problèmes", "Ver problemas", "Ver problemas"],
        "Indexed record diagnostics": ["已索引記錄診斷", "索引済み記録の診断", "인덱싱된 기록 진단", "Diagnóstico de registros indexados", "Diagnose indexierter Einträge", "Diagnostic des enregistrements indexés", "Diagnóstico de registos indexados", "Diagnóstico de registros indexados"],
        "Indexed source access errors": ["索引來源存取異常", "索引ソースのアクセスエラー", "인덱스 소스 접근 오류", "Errores de acceso a fuentes indexadas", "Zugriffsfehler indexierter Quellen", "Erreurs d’accès aux sources indexées", "Erros de acesso às fontes indexadas", "Erros de acesso às fontes indexadas"],
        "Missing source files": ["來源檔案缺失", "ソースファイル欠落", "누락된 소스 파일", "Archivos fuente ausentes", "Fehlende Quelldateien", "Fichiers source manquants", "Ficheiros de origem em falta", "Arquivos de origem ausentes"],
        "Malformed record lines": ["解析失敗行數", "解析失敗行数", "파싱 실패 행 수", "Líneas no válidas", "Fehlerhafte Datensatzzeilen", "Lignes non analysables", "Linhas de registos inválidas", "Linhas de registros inválidas"],
        "No indexed files are confirmed missing. See scan issues above for reading failures.": ["未發現已確認缺失的索引檔案；讀取問題見上方掃描問題。", "索引ファイルの欠落は確認されていません。読み取り失敗は上記のスキャン問題を参照してください。", "누락이 확인된 인덱스 파일은 없습니다. 읽기 실패는 위 스캔 문제를 확인하세요.", "No hay archivos indexados confirmados como ausentes. Consulta arriba los errores de lectura.", "Keine indexierten Dateien fehlen nachweislich. Lesefehler stehen oben unter Scan-Probleme.", "Aucun fichier indexé n’est confirmé manquant. Consultez les problèmes d’analyse ci-dessus.", "Nenhum ficheiro indexado está confirmado como ausente. Veja acima os problemas de leitura.", "Nenhum arquivo indexado está confirmado como ausente. Veja acima os problemas de leitura."],
        "Activity index format could not be recognized. Previous records were retained.": ["活動索引格式無法識別，已保留上次記錄。", "活動索引の形式を認識できません。前回の記録を保持しました。", "활동 인덱스 형식을 인식하지 못해 이전 기록을 유지했습니다.", "Formato del índice de actividad no reconocido. Se conservaron los registros anteriores.", "Aktivitätsindexformat nicht erkannt. Bisherige Einträge bleiben erhalten.", "Format de l’index d’activité non reconnu. Les anciens enregistrements sont conservés.", "Formato do índice de atividade não reconhecido. Registos anteriores mantidos.", "Formato do índice de atividade não reconhecido. Registros anteriores mantidos."],
        "%d of %d usage metadata records could not be recognized. Cached usage was retained.": ["%d / %d 條用量中繼資料無法識別，已保留快取統計。", "%d / %d件の利用メタデータを認識できません。キャッシュを保持しました。", "%d / %d개 사용량 메타데이터를 인식하지 못해 캐시를 유지했습니다.", "No se reconocieron %d de %d metadatos de uso. Se conservó la caché.", "%d von %d Nutzungsmetadaten nicht erkannt. Zwischengespeicherte Nutzung bleibt erhalten.", "%d métadonnées d’utilisation sur %d non reconnues. Le cache est conservé.", "%d de %d metadados de utilização não reconhecidos. Cache mantida.", "%d de %d metadados de uso não reconhecidos. Cache mantido."],
        "Scan did not complete; the number of affected sources is unknown.": ["掃描未完成，無法確認受影響來源數量。", "スキャン未完了。影響を受けるソース数は不明です。", "스캔이 완료되지 않아 영향받는 소스 수를 알 수 없습니다.", "Escaneo incompleto; se desconoce cuántas fuentes están afectadas.", "Scan unvollständig; Anzahl betroffener Quellen unbekannt.", "Analyse incomplète ; nombre de sources affectées inconnu.", "Análise incompleta; número de fontes afetadas desconhecido.", "Verificação incompleta; número de fontes afetadas desconhecido."],
        "No readable sources were found; existing cached data was not revalidated.": ["本次未找到可讀取來源，已有快取未重新驗證。", "読み取り可能なソースが見つからず、既存キャッシュは再検証されていません。", "읽을 수 있는 소스를 찾지 못해 기존 캐시를 재검증하지 않았습니다.", "No se encontraron fuentes legibles; la caché existente no se revalidó.", "Keine lesbaren Quellen gefunden; vorhandener Cache wurde nicht erneut geprüft.", "Aucune source lisible trouvée ; le cache existant n’a pas été revalidé.", "Não foram encontradas fontes legíveis; a cache não foi revalidada.", "Não foram encontradas fontes legíveis; o cache não foi revalidado."],
        "Query accounts, encrypted local credentials, and automatic token renewal.": ["查詢帳號、本機加密憑據與自動權杖續期。", "照会用アカウント、ローカル暗号化認証情報、自動トークン更新。", "조회 계정, 로컬 암호화 자격 증명 및 자동 토큰 갱신.", "Cuentas de consulta, credenciales locales cifradas y renovación automática de tokens.", "Abfragekonten, lokal verschlüsselte Zugangsdaten und automatische Token-Erneuerung.", "Comptes de consultation, identifiants locaux chiffrés et renouvellement automatique des jetons.", "Contas de consulta, credenciais locais cifradas e renovação automática de tokens.", "Contas de consulta, credenciais locais criptografadas e renovação automática de tokens."],
        "Organized overview pages, inline details, and reset card history.": ["分類總覽、頁內詳情與重置卡歷史。", "分類された概要、ページ内詳細、リセットカード履歴。", "분류된 개요, 페이지 내 상세 및 초기화 카드 기록.", "Resumen organizado, detalles en la misma página e historial de tarjetas de reinicio.", "Geordnete Übersicht, Details auf derselben Seite und Reset-Kartenverlauf.", "Vue d’ensemble organisée, détails sur place et historique des cartes de réinitialisation.", "Resumo organizado, detalhes na página e histórico de cartões de reposição.", "Visão geral organizada, detalhes na página e histórico de cartões de redefinição."],
        "Scan warnings now show source details and retry actions; unknown counts are not shown as zero.": ["掃描警告顯示來源詳情與重試操作；未知數量不再顯示為 0。", "スキャン警告にソース詳細と再試行を追加。不明な件数は0と表示しません。", "스캔 경고에 소스 상세와 재시도를 추가하고 알 수 없는 수를 0으로 표시하지 않습니다.", "Los avisos muestran fuentes y reintentos; los recuentos desconocidos no se muestran como cero.", "Scan-Warnungen zeigen Quellen und Wiederholung; unbekannte Anzahlen werden nicht als null angezeigt.", "Les alertes affichent les sources et permettent de réessayer ; les nombres inconnus ne valent pas zéro.", "Avisos mostram fontes e permitem repetir; contagens desconhecidas não aparecem como zero.", "Avisos mostram fontes e permitem tentar novamente; contagens desconhecidas não aparecem como zero."],
    ]
    return rows.mapValues { Dictionary(uniqueKeysWithValues: zip(languages, $0)) }
}()
