import Foundation

let queryAccountTranslations: [String: [AppLanguage: String]] = {
    let languages: [AppLanguage] = [.traditionalChinese, .japanese, .korean, .spanish, .german, .french, .portuguese, .portugueseBrazil]
    let rows: [String: [String]] = [
        "Restored the full quota dashboard for the current Codex account, keeping account switching, management, and nicknames.": [
            "恢復目前 Codex 帳號的完整額度首頁，保留帳號切換、帳號管理和備註。",
            "現在の Codex アカウントの利用枠ダッシュボードを復元しました。アカウントの切り替え、管理、ニックネームは引き続き利用できます。",
            "현재 Codex 계정의 전체 한도 대시보드를 복원하고 계정 전환, 관리 및 별명 기능을 유지했습니다.",
            "Se ha restaurado el panel completo de cuota de la cuenta actual de Codex, manteniendo el cambio de cuentas, la gestión y los alias.",
            "Das vollständige Kontingent-Dashboard für das aktuelle Codex-Konto wurde wiederhergestellt. Kontowechsel, Verwaltung und Spitznamen bleiben erhalten.",
            "Le tableau de bord complet du quota du compte Codex actuel a été rétabli, avec le changement de compte, la gestion et les surnoms.",
            "Foi restaurado o painel completo de quota da conta Codex atual, mantendo a troca de contas, a gestão e as alcunhas.",
            "O painel completo de cota da conta atual do Codex foi restaurado, mantendo a troca de contas, o gerenciamento e os apelidos."
        ],
        "Paste the authorization code from your browser": ["貼上瀏覽器回傳的授權碼", "ブラウザに表示された認証コードを貼り付け", "브라우저의 인증 코드를 붙여넣으세요", "Pega el código de autorización del navegador", "Autorisierungscode aus dem Browser einfügen", "Collez le code d’autorisation du navigateur", "Cole o código de autorização do navegador", "Cole o código de autorização do navegador"],
        "Complete authorization": ["完成授權", "認証を完了", "인증 완료", "Completar autorización", "Autorisierung abschließen", "Terminer l’autorisation", "Concluir autorização", "Concluir autorização"],
        "Account management": ["帳號管理", "アカウント管理", "계정 관리", "Gestión de cuentas", "Kontoverwaltung", "Gestion des comptes", "Gestão de contas", "Gerenciamento de contas"],
        "Reauthorization required": ["需要重新授權", "再認証が必要", "재인증 필요", "Requiere autorización", "Erneute Autorisierung erforderlich", "Réautorisation requise", "Reautorização necessária", "Reautorização necessária"],
        "Verification or query failed. Last successful data was retained.": ["驗證或查詢失敗，已保留上次成功資料。", "検証または取得に失敗しました。前回のデータを保持しています。", "검증 또는 조회에 실패했습니다. 이전 데이터를 유지합니다.", "Error de verificación o consulta. Se conservan los últimos datos.", "Prüfung oder Abfrage fehlgeschlagen. Letzte Daten bleiben erhalten.", "Échec de vérification ou de requête. Les dernières données sont conservées.", "Falha na verificação ou consulta. Os últimos dados foram mantidos.", "Falha na verificação ou consulta. Os últimos dados foram mantidos."],
        "Add and verify an account to view live quota": ["新增並驗證帳號後查看即時額度", "アカウントを追加・検証して利用枠を表示", "실시간 한도를 보려면 계정을 추가하고 검증하세요", "Añade y verifica una cuenta para ver la cuota actual", "Konto hinzufügen und prüfen, um aktuelle Kontingente zu sehen", "Ajoutez et vérifiez un compte pour voir le quota actuel", "Adicione e verifique uma conta para ver a quota atual", "Adicione e verifique uma conta para ver a cota atual"],
        "Verified imported credentials": ["已驗證的匯入憑證", "検証済みのインポート認証情報", "검증된 가져온 인증 정보", "Credenciales importadas verificadas", "Geprüfte importierte Zugangsdaten", "Identifiants importés vérifiés", "Credenciais importadas verificadas", "Credenciais importadas verificadas"],
        "Only the query identity changes, not the tool login.": ["僅切換查詢身分，不改變工具登入。", "照会するアカウントのみ変更し、ツールのログインは変更しません。", "조회 계정만 변경하며 도구 로그인은 변경하지 않습니다.", "Solo cambia la identidad de consulta, no el inicio de sesión de la herramienta.", "Nur die Abfrageidentität ändert sich, nicht die Tool-Anmeldung.", "Seule l’identité de requête change, pas la connexion de l’outil.", "Só muda a identidade da consulta, não a sessão da ferramenta.", "Só muda a identidade da consulta, não o login da ferramenta."],
        "Browser authorization": ["瀏覽器授權", "ブラウザで認証", "브라우저 인증", "Autorizar en navegador", "Im Browser autorisieren", "Autoriser dans le navigateur", "Autorizar no navegador", "Autorizar no navegador"],
        "Import local account": ["匯入本機帳號", "ローカルアカウントをインポート", "로컬 계정 가져오기", "Importar cuenta local", "Lokales Konto importieren", "Importer un compte local", "Importar conta local", "Importar conta local"],
        "Import credential file": ["匯入憑證檔案", "認証ファイルをインポート", "인증 파일 가져오기", "Importar archivo de credenciales", "Zugangsdaten importieren", "Importer un fichier d’identifiants", "Importar ficheiro de credenciais", "Importar arquivo de credenciais"],
        "Imported credentials are query-only. Shared tokens are not rotated; reimport or authorize independently when they expire.": ["匯入憑證僅供查詢，不輪換共用權杖；到期後重新匯入或獨立授權。", "インポート情報は照会専用です。共有トークンは更新しません。有効期限後は再インポートまたは独立認証してください。", "가져온 인증은 조회 전용입니다. 공유 토큰은 갱신하지 않습니다. 만료 시 다시 가져오거나 별도로 인증하세요.", "Las credenciales importadas solo permiten consultas. Los tokens compartidos no se renuevan; reimporta o autoriza por separado al caducar.", "Importierte Zugangsdaten dienen nur zur Abfrage. Gemeinsame Tokens werden nicht erneuert; nach Ablauf erneut importieren oder separat autorisieren.", "Les identifiants importés servent uniquement aux requêtes. Les jetons partagés ne sont pas renouvelés ; réimportez ou autorisez séparément à l’expiration.", "As credenciais importadas servem só para consultas. Os tokens partilhados não são renovados; reimporte ou autorize separadamente quando expirarem.", "As credenciais importadas servem só para consultas. Os tokens compartilhados não são renovados; reimporte ou autorize separadamente quando expirarem."],
        "Credential JSON": ["憑證 JSON", "認証情報 JSON", "인증 정보 JSON", "JSON de credenciales", "Zugangsdaten-JSON", "JSON d’identifiants", "JSON de credenciais", "JSON de credenciais"],
        "Verify and add": ["驗證並新增", "検証して追加", "검증 후 추가", "Verificar y añadir", "Prüfen und hinzufügen", "Vérifier et ajouter", "Verificar e adicionar", "Verificar e adicionar"],
        "Verify": ["驗證", "検証", "검증", "Verificar", "Prüfen", "Vérifier", "Verificar", "Verificar"],
        "Remove credentials": ["移除憑證", "認証情報を削除", "인증 정보 제거", "Eliminar credenciales", "Zugangsdaten entfernen", "Supprimer les identifiants", "Remover credenciais", "Remover credenciais"],
        "Cannot read credential file": ["無法讀取憑證檔案", "認証ファイルを読み取れません", "인증 파일을 읽을 수 없습니다", "No se puede leer el archivo de credenciales", "Zugangsdaten-Datei nicht lesbar", "Impossible de lire le fichier d’identifiants", "Não é possível ler o ficheiro de credenciais", "Não é possível ler o arquivo de credenciais"],
        "Remove only QuotaLens credentials. All history and tool logins are preserved.": ["僅移除 QuotaLens 憑證，保留全部歷史與工具登入。", "QuotaLens の認証情報のみ削除します。履歴とツールのログインは保持されます。", "QuotaLens 인증 정보만 제거합니다. 기록과 도구 로그인은 유지됩니다.", "Solo se eliminan las credenciales de QuotaLens. Se conservan el historial y las sesiones de las herramientas.", "Nur QuotaLens-Zugangsdaten entfernen. Verlauf und Tool-Anmeldungen bleiben erhalten.", "Seuls les identifiants QuotaLens sont supprimés. L’historique et les connexions des outils sont conservés.", "Remover apenas credenciais QuotaLens. O histórico e as sessões das ferramentas são mantidos.", "Remover apenas credenciais QuotaLens. O histórico e os logins das ferramentas são mantidos."],
        "Verified": ["已驗證", "検証済み", "검증됨", "Verificado", "Geprüft", "Vérifié", "Verificado", "Verificado"],
        "Not verified": ["待驗證", "未検証", "검증 대기", "Sin verificar", "Ungeprüft", "Non vérifié", "Por verificar", "Não verificado"],
        "This page summarizes local records. View live account quota in Quota Overview.": ["本頁統計本機記錄；即時帳號額度請查看額度概覽。", "このページはローカル記録の集計です。アカウントの最新利用枠は利用枠概要で確認してください。", "이 페이지는 로컬 기록을 집계합니다. 실시간 계정 한도는 한도 개요에서 확인하세요.", "Esta página resume registros locales. Consulta la cuota actual en Resumen de cuota.", "Diese Seite fasst lokale Daten zusammen. Aktuelle Kontingente stehen in der Kontingentübersicht.", "Cette page résume les données locales. Consultez le quota actuel dans la vue d’ensemble.", "Esta página resume registos locais. Consulte a quota atual na visão geral.", "Esta página resume registros locais. Consulte a cota atual na visão geral."]
    ]
    return rows.mapValues { Dictionary(uniqueKeysWithValues: zip(languages, $0)) }
}()
